# Generated by Django 5.1.14 on 2025-11-18 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='General', max_length=100),
            preserve_default=False,
        ),
    ]
