# Generated by Django 5.1.15 on 2025-12-25 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_header_image_alter_post_text'),
        ('blog', '0004_post_header_image_alter_post_text'),
    ]

    operations = [
    ]
